name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Or whatever branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add steps to build your web app here (e.g., npm install, npm run build)
      # If you don't have a build step, you can skip this section.
      # Example:
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live # Or use 'preview' for preview channels
          projectId: chat-room-1d2d4 # Replace with your Firebase project ID
          entryPoint: ./ # if you have firebase.json in the root

